### ISSUE TITLE
Permission Denial for PR

### ISSUE THREAD

**Issue by aritraroy24** [Leticia-maria/Introduction.jl#3]
I have played around with the mini guessing game and introduced more conditions. I have created a **`minigame-users`** folder under the `Scripts` folder. Inside that newly created folder I have added my own version as *minigame-aritraroy24.jl*. 

I have created a new branch `aritraroy24` for this repo and tried to send a PR. So that others can submit their own versions in that same folder. While `git push --set-upstream origin aritraroy24` I'm getting the permission denial error like following. If I do a `git status` now, it says *nothing to commit, working tree clean*.

![image](https://github.com/Leticia-maria/Introduction.jl/assets/65696941/9ce09445-2b91-4c2a-afee-ed01ea0b2a0c)

**Comment by Leticia-maria** [comment]
Hey @aritraroy24 you can post your solution in the show and tell discussion! https://github.com/Leticia-maria/Introduction.jl/discussions/5 
We won't be working on PRs for the practice (repo + branch protected 😄 )
